server:
  port: 8089
  session:
  cookie:
    name: sessionid
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/mydb?serverTimezone=GMT%2B8&useUnicode=true&autoReconnect=true&useAffectedRows=true&characterEncoding=utf8
    url: jdbc:mysql://8.134.191.139:3306/mydb?serverTimeznotallow=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root-ps@123456
    #password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: "classpath*:com/example/LqcSpringBoot/mapperXml/*.xml"
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl